version: '3.8'

services:
  # 1. Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres-finance
    restart: always
    environment:
      POSTGRES_USER: deployed
      POSTGRES_PASSWORD: 4KHxPMHsn7kePY9RMPpU5SUQKo42LBc6
      POSTGRES_DB: financeapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Backend NestJS
  api:
    build: 
      context: ./backend
    container_name: nest-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://deploy:4KHxPMHsn7kePY9RMPpU5SUQKo42LBc6@db:5432/financeapp
    depends_on:
      - db

  # 3. Frontend React (Servido via Nginx)
  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata: